name: SuperHarvesterHoe
version: '${project.version}'
main: me.c0dev.superharvesterhoe.Main
api-version: 1.18

commands:
  giveSHarvesterHoe:
    description: Gives the player a harvester hoe
    usage: /giveSHarvesterHoe